### ISSUE TITLE
Feature Request: Text field instead of single line input

### ISSUE THREAD

**Issue by DasJott** [sainathmurali/top-panel-note#1]
Despite the screenshot on "GNOME Extension" webpage, where there's multiline text possible, this extension only provided me with a single line input field.
Even pasting multiline text resulted in a (very long) single line.

Running Fedora workstation 40 with all recent updates here.

**Comment by sainathmurali** [comment]
Hi @DasJott!

I didn't notice this as pasting was working perfectly for me. Thank you for pointing out. I'll try to implement this as soon as possible. In the meantime, you can try the following way as an alternative.

  - If you want to format the note properly, you can edit the text file containing the information (~/.cache/top_panel_note_cache.txt).
  - Then press Alt+F2, type 'r' and press enter↵ to restart the gnome-shell to take effects.

**Comment by sainathmurali** [comment]
I updated the extension with multiline input feature. It's under review and will be available soon.

**Comment by DasJott** [comment]
Thank you so much - you're the best 👍🏻 
This extension seems so simple but is such a great thing. Being able to just put some notes there and therefore not having to keep that in mind yourself is priceless!

**Comment by empty2k** [comment]
Since the last update I can no longer enter text, the text area is only highlighted by the mouseover. I am using Gnome 45, any idea why this might be? 
![grafik](https://github.com/user-attachments/assets/d3265a4b-a6ba-4363-9a57-3cf5d18cd200)

**Comment by sainathmurali** [comment]
@empty2k Please run the following command in terminal 
```
 journalctl /usr/bin/gnome-shell -f
```
Press Alt + F2 and type 'r' after running the above command and send the output of the command from terminal.

**Comment by empty2k** [comment]
```shell
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x5843a1ddf0c0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<ClutterText>:0x5843a1d725d0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x5843a1ddf0c0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<ClutterText>:0x5843a1d725d0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x5843a1ddf0c0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<ClutterText>:0x5843a1d725d0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x5843a1ddf0c0] is on because it needs an allocation.
Sep 23 09:06:03 pika gnome-shell[2130]: Can't update stage views actor <unnamed>[<ClutterText>:0x5843a1d725d0] is on because it needs an allocation.
Sep 23 09:06:16 pika gnome-shell[2130]: Starting subprocess: ["/home/sascha/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm","--gapplication-service"]
Sep 23 09:06:16 pika gnome-shell[2130]: com.github.amezin.ddterm: name owner changed to ":1.208"
Sep 23 09:06:42 pika gnome-shell[2130]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
Sep 23 09:06:42 pika gnome-shell[2130]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
Sep 23 09:06:42 pika gnome-shell[2130]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
Sep 23 09:06:44 pika gnome-shell[2130]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead

```

**Comment by DasJott** [comment]
The current version is already great so far!
One little thing though:
To set the focus (to add more text) you have to click exactly on the existing text. Every click within the window/textfield besides the existing text closes the window.

Two suggestions to improve:
Make the window resizable (lower right corner)
Set the focus to the end of existing text on click anywhere in the window.

Keep up the good work, I love it :)

Edit:
Just noticed: Arrow keys - left and right works as expected. Up and Down somehow vanishes the cursor and sets the focus onto the panel. Is it possible to fix that as well?

**Comment by sainathmurali** [comment]
@empty2k None of these entries are related to the current extension. Can you try uninstalling and reinstalling?

**Comment by sainathmurali** [comment]
@DasJott I gave it a try to fix the focus issue even while creating. But it seems there is no straightforward way to do that. I'll try my best. Regarding the resizing I'm not aware of any existing options to do that. If you find any other extension having that functionality, please let me know. I'll try to reverse engineer.

**Comment by sainathmurali** [comment]
I have fixed the issues mentioned here. The new version will be available for update on the gnome extensions website soon.
