### ISSUE TITLE
Unable to activate top-panel-note Ubuntu 24.10 and Gnome 47

### ISSUE THREAD

**Issue by JekoTronik** [sainathmurali/top-panel-note#2]
The extensions'panel says that the version of the extension (4) is not compatible with the current version of Gnome (?) so it has been disabled.

I am not used to gnome extension issues. Let me know if you need more details.

**Comment by sainathmurali** [comment]
I'm working on it. I will update it as soon as possible.

**Comment by sainathmurali** [comment]
Updated the extension. It will be available for update in the gnome-extensions soon.
